runtime: php55
threadsafe: true

# instance_class: F1
# automatic_scaling:
#  min_idle_instances: automatic
#  max_idle_instances: automatic
#  min_pending_latency: automatic
#  max_pending_latency: automatic

handlers:
  - url: /GAE/contacts\.php
    script: /GAE/contacts.php
    secure: always

  - url: /GAE/detail\.php
    script: /GAE/detail.php
    secure: always

  - url: /GAE/form\.php
    script: /GAE/form.php
    secure: always

  - url: /GAE/profile\.php
    script: /GAE/profile.php
    secure: always

  - url: /GAE/messageBoard\.php
    script: /GAE/messageBoard.php
    secure: always

  - url: /GAE/message\.php
    script: /GAE/message.php
    secure: always

  - url: /JJ/signin\.php
    script: /JJ/signin.php
    secure: always

  - url: /JJ/mid\.php
    script: /JJ/mid.php
    secure: always

  # - url: /PHP
  #   script: /PHP
  #   secure: always

  # - url: /PHP/(.*\.inc)$
  #   static_files: PHP
  #   upload: PHP/(.*\.inc)$

  - url: /.*
    script: index.php
    secure: always

  - url: /static
    static_dir: static

skip_files:
- /PHP/DB/