runtime: php
env: flex
threadsafe: true

runtime_config:
  document_root: .

instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

handlers:

  - url: /GAE/contacts.php
    script: contacts.php
    secure: always

  - url: /GAE/form.php
    script: form.php
    secure: always

  - url: /GAE/profile.php
    script: profile.php
    secure: always

  - url: /JJ/signin.php
    script: signin.php
    secure: always

  - url: /.*
    script: index.php
    secure: always