runtime: php55
# threadsafe: true

# instance_class: F1
# automatic_scaling:
#  min_idle_instances: automatic
#  max_idle_instances: automatic
#  min_pending_latency: automatic
#  max_pending_latency: automatic

handlers:
  - url: /GAE/contacts.php
    script: /GAE/contacts.php
    secure: always

  - url: /GAE/form.php
    script: /GAE/form.php
    secure: always

  - url: /GAE/profile.php
    script: /GAE/profile.php
    secure: always

  - url: /JJ/signin.php
    script: /JJ/signin.php
    secure: always

  - url: /.*
    script: index.php
    secure: always