runtime: php55
version: 1
threadsafe: true

instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: automatic

handlers:
- url: /
  script: index.html
  secure: always

- url: /index\.html
  script: index.html
  secure: always

- url: /profile\.html
  script: profile.html
  secure: always

- url: /.*
  script: index.html
  secure: always