runtime: php55
api_version: 1

handlers:
- url: /
  script: index.html
  secure: always

- url: /index\.html
  script: index.html
  secure: always

- url: /profile\.html
  script: profile.html
  secure: always

- url: /.*
  script: index.html
  secure: always