<?php
$sqls = [
"SELECT sno, name, address FROM students",
"SELECT * FROM students",
"SELECT DISTINCT credits FROM courses",
"SELECT sno AS ID, name AS StudentName, address AS Home FROM students",
"SELECT * FROM students WHERE sno='S003'",
"SELECT * FROM students WHERE address LIKE '%新%'",
"SELECT * FROM students WHERE birthday LIKE '1__6%'",
"SELECT * FROM courses WHERE credits=3",
"SELECT * FROM students WHERE birthday='1995-07-22'",
"SELECT * FROM students WHERE sno<='S003' AND name LIKE '%陳%'",
"SELECT * FROM Students WHERE sno<'S003' OR name LIKE '%張%'",
"SELECT * FROM students WHERE sno>='S002' AND sno<='S004' OR name LIKE '%陳%'",
"SELECT * FROM students WHERE (name LIKE '%陳%' OR address LIKE '新北巿' ) AND sno<'S002'",
"SELECT * FROM courses WHERE credits>2 ORDER BY credits ASC",
"SELECT * FROM courses WHERE credits>2 ORDER BY credits DESC",
"SELECT * FROM students WHERE birthday BETWEEN '1997-01-01' AND '1997-12-31'",
"SELECT * FROM students WHERE sno IN ('S001', 'S003', 'S004')",
"SELECT * FROM students WHERE sno NOT IN ('S001', 'S003', 'S004')",
"SELECT * FROM students LIMIT 1, 3",
"SELECT COUNT(*) FROM students",
"SELECT AVG(credits) FROM courses",
"SELECT MAX(credits) FROM courses",
"SELECT MIN(credits) FROM courses",
"SELECT SUM(credits) FROM courses",
"SELECT COUNT(*) FROM classes WHERE sno = (SELECT sno FROM students WHERE name='陳會安')",
"SELECT students.sno, students.name, classes.cno FROM students INNER JOIN classes ON students.sno = classes.sno",
"SELECT students.*, classes.cno FROM students LEFT JOIN classes ON students.sno = classes.sno",
"SELECT classes.sno, courses.* FROM classes RIGHT JOIN courses ON classes.cno = courses.cno",
"INSERT INTO students (sno, name, address, birthday) VALUES ('S007','小龍女','新北巿新店區','1997-04-11')",
"SELECT * FROM students",
"UPDATE students SET address='新北巿三重區' WHERE sno = 'S007'",
"SELECT * FROM students",
"DELETE FROM students WHERE sno = 'S007'",
"SELECT * FROM students"
];
?>